version: '3.8'
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=seu-admin@landis-neuropsicologia.com.br'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './letsencrypt:/letsencrypt'

  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    image: landing-page
    container_name: website
    restart: always
    labels:
      - 'traefik.enable=true'

      # HTTPS Router (domínio principal)
      - 'traefik.http.routers.landing.rule=Host(`landis-neuropsicologia.com.br`)'
      - 'traefik.http.routers.landing.entrypoints=websecure'
      - 'traefik.http.routers.landing.tls.certresolver=myresolver'
      - 'traefik.http.routers.landing.service=landing'

      # HTTP Router para qualquer host (IP, localhost, etc.)
      - 'traefik.http.routers.landing-http.rule=HostRegexp(`{host:.+}`)'
      - 'traefik.http.routers.landing-http.entrypoints=web'
      - 'traefik.http.routers.landing-http.priority=1'
      - 'traefik.http.routers.landing-http.service=landing'

      # HTTP Router com redirecionamento para domínio principal
      - 'traefik.http.routers.landing-redirect.rule=Host(`landis-neuropsicologia.com.br`)'
      - 'traefik.http.routers.landing-redirect.entrypoints=web'
      - 'traefik.http.routers.landing-redirect.middlewares=redirect-to-https'
      - 'traefik.http.routers.landing-redirect.priority=2'

      # Middleware de redirecionamento
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'

      # Configuração do serviço
      - 'traefik.http.services.landing.loadbalancer.server.port=80'
