# docker-compose.yml
version: '3.8'

services:
  website:
    build: .
    container_name: meu-site-container
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS (se configurar SSL)
    volumes:
      # Para logs (opcional)
      - ./logs/nginx:/var/log/nginx
    networks:
      - web
    labels:
      # Labels para Traefik (se usar)
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`seu-dominio.com`)"

  # Exemplo de outros serviços que você pode ter
  # database:
  #   image: postgres:15
  #   container_name: db-container
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - web

networks:
  web:
    external: true

# volumes:
#   postgres_data:
