version: '3.8'
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik-dev
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    image: landing-page
    container_name: website-dev
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.landing.rule=Host(`localhost`)'
      - 'traefik.http.routers.landing.entrypoints=web'
      - 'traefik.http.services.landing.loadbalancer.server.port=80'
